# NusaSynth — Metrik Bab IV: Evaluasi Kualitas Data Sintetis

Notebook ini menghitung metrik **Evaluasi Kualitas Data Sintetis** (Bab III, subbab Evaluasi), mengikuti struktur dan penamaan prosa docx. Tiga kelompok metrik yang saling melengkapi:

1. **Pipeline Outcome Breakdown** (persamaan 3.1-3.8) - komposisi hasil *pipeline*.
2. **Kemurnian Linguistik dan Kesesuaian Distribusi Statistik** (persamaan 3.9-3.14) - sifat kalimat yang diterima.
3. **Konsistensi LLM terhadap Prediksi Classifier** (persamaan 3.15-3.16) - independensi keputusan validator.

> **Evaluasi Performa Downstream Task** (Accuracy & F1-Macro) ada di notebook terpisah `finetune_nusabert.ipynb`.

Sel bertanda **(Pendukung)** = analisis pelengkap untuk pembahasan kualitatif, tidak memiliki persamaan di docx.

**Bahasa target**: 7 bahasa (ace, ban, bjn, jav, mad, min, sun).

## Setup

In [1]:
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

pd.set_option('display.max_colwidth', 150)
pd.set_option('display.width', 200)

ROOT = Path('y:/Michh/Python/Projects/MAGenerator')
sys.path.insert(0, str(ROOT))
from NusaSynth.config import synthetic_dir  # folder-per-run: outputs/synthetic/<run_id>/<lang>/ (latest run / NUSASYNTH_RUN_ID)

LANGS = ['ace', 'ban', 'bjn', 'jav', 'mad', 'min', 'sun']
SENTENCES_PER_SEED = 5
BATCH_SIZE = 5  # sesuai NusaSynth/config.py

# Load semua data: seed (train), synthetic, valid, test, pipeline log
seed_dfs, syn_dfs, valid_dfs, test_dfs, log_dfs = {}, {}, {}, {}, {}
for lang in LANGS:
    seed_p  = ROOT / f'data/nusax_senti/{lang}/train.csv'
    syn_p   = synthetic_dir(lang) / 'synthetic.csv'
    valid_p = ROOT / f'data/nusax_senti/{lang}/valid.csv'
    test_p  = ROOT / f'data/nusax_senti/{lang}/test.csv'
    log_p   = synthetic_dir(lang) / 'pipeline_log.jsonl'
    if not all(p.exists() for p in [seed_p, syn_p, log_p, valid_p, test_p]):
        print(f'  [{lang}] SKIP: file tidak lengkap')
        continue
    seed_dfs[lang]  = pd.read_csv(seed_p)
    syn_dfs[lang]   = pd.read_csv(syn_p)
    valid_dfs[lang] = pd.read_csv(valid_p)
    test_dfs[lang]  = pd.read_csv(test_p)
    with open(log_p, encoding='utf-8') as f:
        log_dfs[lang] = pd.DataFrame([json.loads(line) for line in f])
    print(f'  [{lang}] seed={len(seed_dfs[lang])} syn={len(syn_dfs[lang])} '
          f'valid={len(valid_dfs[lang])} test={len(test_dfs[lang])} log={len(log_dfs[lang])}')

  [ace] seed=500 syn=2268 valid=100 test=400 log=3930
  [ban] seed=500 syn=2400 valid=100 test=400 log=3653
  [bjn] seed=500 syn=2366 valid=100 test=400 log=3705
  [jav] seed=500 syn=2430 valid=100 test=400 log=3461
  [mad] seed=500 syn=2298 valid=100 test=400 log=4040
  [min] seed=500 syn=2381 valid=100 test=400 log=3664

  [sun] seed=500 syn=2447 valid=100 test=400 log=3465

## 1. Pipeline Outcome Breakdown (persamaan 3.1-3.8)

Menggambarkan komposisi hasil akhir *pipeline* dengan membagi seluruh kalimat ke dalam lima kategori *outcome* yang saling eksklusif. Mengukur efisiensi Generator pada percobaan pertama serta kontribusi *feedback loop* dalam menyelamatkan kalimat yang awalnya gagal validasi. Persentase dihitung relatif terhadap total kalimat *terminal outcome* (persamaan 3.1-3.2).

### Kategori Outcome & Filter Rate (persamaan 3.3-3.8)

- **Attempt 0** (pers. 3.3): lolos di percobaan pertama tanpa *retry*
- **Attempt 1** (pers. 3.4): lolos setelah satu kali *retry*
- **Attempt 2** (pers. 3.5): lolos setelah dua kali *retry*
- **Discard** (pers. 3.6): dibuang setelah mencapai *max retry*
- **Cross-batch Dedup** (pers. 3.7): valid tetapi difilter karena terlalu mirip kalimat tersimpan
- **Filter Rate** (pers. 3.8) = Attempt 0 + 1 + 2, efisiensi *pipeline end-to-end*

In [2]:
rows = []
for lang in LANGS:
    if lang not in log_dfs:
        continue
    log_df = log_dfs[lang]
    o = log_df['outcome'].value_counts()
    n_disc = o.get('discarded', 0)
    n_dedup = o.get('dedup_filtered', 0)

    # Per-attempt acceptance: kalimat accepted dengan retry_count tertentu
    accepted_log = log_df[log_df['outcome'] == 'accepted']
    if 'retry_count' in accepted_log.columns:
        att_dist = accepted_log['retry_count'].value_counts().to_dict()
        att_0 = att_dist.get(0, 0)
        att_1 = att_dist.get(1, 0)
        att_2 = att_dist.get(2, 0)
    else:
        att_0 = att_1 = att_2 = 0

    n_acc = att_0 + att_1 + att_2
    total_terminal = n_acc + n_disc + n_dedup

    rows.append({
        'lang': lang,
        'att_0': att_0,
        'att_1': att_1,
        'att_2': att_2,
        'discard': n_disc,
        'dedup': n_dedup,
        'total': total_terminal,
        'filter_rate%': round(n_acc / total_terminal * 100, 2) if total_terminal else 0,
    })

display(pd.DataFrame(rows))

  lang  att_0  att_1  att_2  discard  dedup  total  filter_rate%
0  ace   1459    640    169      221     11   2500         90.72
1  ban   1556    721    123       86     14   2500         96.00
2  bjn   1547    696    123      128      6   2500         94.64
3  jav   1658    712     60       58     12   2500         97.20
4  mad   1336    756    206      164     38   2500         91.92
5  min   1552    722    107      109     10   2500         95.24
6  sun   1670    689     88       47      6   2500         97.88

### (+) Discard Rate per Label

Cek label mana yang paling susah digenerate (highest discard rate).

In [3]:
rows = []
for lang in LANGS:
    if lang not in log_dfs:
        continue
    ct = pd.crosstab(log_dfs[lang]['target_label'], log_dfs[lang]['outcome'])
    row = {'lang': lang}
    for label in ['negative', 'neutral', 'positive']:
        if label in ct.index:
            r = ct.loc[label]
            acc  = r.get('accepted', 0)
            disc = r.get('discarded', 0)
            ded  = r.get('dedup_filtered', 0)
            retr = r.get('retried', 0)
            terminal = acc + disc + ded      # hasil TERMINAL (konsisten Filter Rate agregat)
            all_att  = terminal + retr       # SEMUA percobaan (termasuk retried)
            row[f'{label}_accept%']  = round(acc  / terminal * 100, 2) if terminal else 0
            row[f'{label}_discard%'] = round(disc / terminal * 100, 2) if terminal else 0
            row[f'{label}_dedup%']   = round(ded  / terminal * 100, 2) if terminal else 0
            row[f'{label}_retry%']   = round(retr / all_att  * 100, 1) if all_att else 0
    rows.append(row)

print("DENOMINATOR (eksplisit, konsisten rumus Pipeline Outcome):")
print("  accept%/discard%/dedup% : basis = hasil TERMINAL label (accepted+discarded+dedup).")
print("       accept% = Filter Rate PER LABEL; +discard%+dedup% = 100%; konsisten Filter Rate agregat 94,80%.")
print("  retry%                  : basis = SEMUA percobaan label (terminal+retried); attempt-level (ilustrasi 4.1).")
print("  Kelas neutral: discard% tertinggi, accept% terendah, retry% tertinggi -> paling sulit dihasilkan.")
print()
_dl = pd.DataFrame(rows)
display(_dl)
print("Discard% per label (basis terminal) - neutral tersulit:")
print(_dl[['lang', 'negative_discard%', 'neutral_discard%', 'positive_discard%']].to_string(index=False))
print()
print("retry% per label (basis semua percobaan) - ilustrasi 4.1 (ace neutral ~49,7):")
print(_dl[['lang', 'negative_retry%', 'neutral_retry%', 'positive_retry%']].to_string(index=False))

DENOMINATOR (eksplisit, konsisten rumus Pipeline Outcome):
  accept%/discard%/dedup% : basis = hasil TERMINAL label (accepted+discarded+dedup).
       accept% = Filter Rate PER LABEL; +discard%+dedup% = 100%; konsisten Filter Rate agregat 94,80%.
  retry%                  : basis = SEMUA percobaan label (terminal+retried); attempt-level (ilustrasi 4.1).
  Kelas neutral: discard% tertinggi, accept% terendah, retry% tertinggi -> paling sulit dihasilkan.

,lang,negative_accept%,negative_discard%,negative_dedup%,negative_retry%,neutral_accept%,neutral_discard%,neutral_dedup%,neutral_retry%,positive_accept%,positive_discard%,positive_dedup%,positive_retry%
0,ace,96.56,3.44,0.00,26.4,75.97,22.18,1.85,49.7,94.07,5.93,0.00,34.4
1,ban,98.96,1.04,0.00,21.5,90.25,7.39,2.35,42.6,96.61,3.39,0.00,32.2
2,bjn,99.38,0.62,0.00,20.3,81.01,18.49,0.50,48.3,98.41,1.27,0.32,29.9
3,jav,98.75,1.25,0.00,19.5,91.93,6.22,1.85,41.0,98.94,0.95,0.11,25.0
4,mad,95.73,3.96,0.31,32.2,85.04,11.60,3.36,48.1,92.38,6.03,1.59,36.0
5,min,99.58,0.42,0.00,20.2,82.35,15.97,1.68,47.0,98.94,1.06,0.00,29.4
6,sun,99.90,0.10,0.00,17.5,93.45,5.55,1.01,40.7,98.62,1.38,0.00,27.2

Discard% per label (basis terminal) - neutral tersulit:
lang  negative_discard%  neutral_discard%  positive_discard%
 ace               3.44             22.18               5.93
 ban               1.04              7.39               3.39
 bjn               0.62             18.49               1.27
 jav               1.25              6.22               0.95
 mad               3.96             11.60               6.03
 min               0.42             15.97               1.06
 sun               0.10              5.55               1.38

retry% per label (basis semua percobaan) - ilustrasi 4.1 (ace neutral ~49,7):
lang  negative_retry%  neutral_retry%  positive_retry%
 ace             26.4            49.7             34.4
 ban             21.5            42.6             32.2
 bjn             20.3            48.3             29.9
 jav             19.5            41.0             25.0
 mad             32.2            48.1             36.0
 min             20.2            47.0             29.4
 sun             17.5            40.7             27.2

### (+) Dekomposisi Pemicu Retry (SV / LV / PSLM)

Mekanisme retry dipicu tiga sumber penolakan yang **saling eksklusif**:
- **SV** — Sentiment Validator menolak (sentimen tidak sesuai target)
- **LV** — Linguistic Validator menolak (bahasa tidak natural / artefak)
- **PSLM** — filter Per-Sentence Length Match mendeteksi *length drift* (`|gen_len − seed_len| > 1.0σ` per label)

**Basis hitung**: HANYA baris `outcome=='retried'` (snapshot penolakan), satu baris per kejadian retry.

> Versi lama menghitung `prev_feedback` berisi `"Length drift"` di **semua** baris log → *over-count* ~2× karena `prev_feedback` ikut terbawa ke baris *attempt* regenerasi berikutnya. Basis `retried`-only memperbaiki ini (PSLM benar = 532, bukan 1043).

**Mutually exclusive**: validasi berjenjang SV → LV → PSLM (LV hanya validasi yang lolos SV; PSLM hanya pada yang lolos SV+LV), jadi tiap retry punya tepat satu pemicu → proporsi menjumlah 100%.

Identifikasi per baris `retried`: `prev_feedback` berisi `"Length drift"` → PSLM; selain itu `sv_verdict=='REJECT'` → SV; `lv_verdict=='REJECT'` → LV.

In [4]:
# A1c. Dekomposisi Pemicu Retry — basis: HANYA baris outcome=='retried'
rows_retry = []
for lang in LANGS:
    if lang not in log_dfs:
        continue
    retried = log_dfs[lang][log_dfs[lang]['outcome'] == 'retried']
    n_sv = n_lv = n_pslm = 0
    for _, r in retried.iterrows():
        fb = r.get('prev_feedback') or ''
        if 'Length drift' in fb:
            n_pslm += 1
        elif r.get('sv_verdict') == 'REJECT':
            n_sv += 1
        elif r.get('lv_verdict') == 'REJECT':
            n_lv += 1
        else:
            n_pslm += 1  # lolos SV+LV tanpa feedback eksplisit -> length drift
    n_retry = n_sv + n_lv + n_pslm
    rows_retry.append({
        'lang': lang, 'N_SV': n_sv, 'N_LV': n_lv, 'N_PSLM': n_pslm, 'N_retry': n_retry,
        'SV%':   round(n_sv   / n_retry * 100, 1) if n_retry else 0,
        'LV%':   round(n_lv   / n_retry * 100, 1) if n_retry else 0,
        'PSLM%': round(n_pslm / n_retry * 100, 1) if n_retry else 0,
    })

df_retry = pd.DataFrame(rows_retry)

# Baris TOTAL (agregat 7 bahasa)
tot = {'lang': 'TOTAL'}
for c in ['N_SV', 'N_LV', 'N_PSLM', 'N_retry']:
    tot[c] = int(df_retry[c].sum())
tot['SV%']   = round(tot['N_SV']   / tot['N_retry'] * 100, 1)
tot['LV%']   = round(tot['N_LV']   / tot['N_retry'] * 100, 1)
tot['PSLM%'] = round(tot['N_PSLM'] / tot['N_retry'] * 100, 1)
df_retry = pd.concat([df_retry, pd.DataFrame([tot])], ignore_index=True)

print("Dekomposisi pemicu retry (basis: baris outcome=='retried'; tiap retry 1 pemicu -> jumlah 100%).")
print("PSLM = pemicu terbanyak: tantangan utama Generator = penyesuaian panjang, bukan sentimen/bahasa.")
print("jav 66.7% PSLM & LV cuma 5.6% -> output jav sudah sangat natural; ace/mad LV tinggi -> artefak/kosakata.")
print()
display(df_retry)
print(f"\nTotal retry events (7 bahasa): {tot['N_retry']}")
print(f"PSLM: {tot['N_PSLM']} ({tot['PSLM%']}%)  |  SV: {tot['N_SV']} ({tot['SV%']}%)  |  LV: {tot['N_LV']} ({tot['LV%']}%)")

Dekomposisi pemicu retry (basis: baris outcome=='retried'; tiap retry 1 pemicu -> jumlah 100%).
PSLM = pemicu terbanyak: tantangan utama Generator = penyesuaian panjang, bukan sentimen/bahasa.
jav 66.7% PSLM & LV cuma 5.6% -> output jav sudah sangat natural; ace/mad LV tinggi -> artefak/kosakata.

    lang  N_SV  N_LV  N_PSLM  N_retry   SV%   LV%  PSLM%
0    ace   441   479     510     1430  30.8  33.5   35.7
1    ban   307   220     626     1153  26.6  19.1   54.3
2    bjn   349   287     569     1205  29.0  23.8   47.2
3    jav   303    59     599      961  31.5   6.1   62.3
4    mad   357   607     576     1540  23.2  39.4   37.4
5    min   367   210     587     1164  31.5  18.0   50.4
6    sun   326    62     577      965  33.8   6.4   59.8
7  TOTAL  2450  1924    4044     8418  29.1  22.9   48.0

Total retry events (7 bahasa): 8418
PSLM: 4044 (48.0%)  |  SV: 2450 (29.1%)  |  LV: 1924 (22.9%)

## 2. Kemurnian Linguistik dan Kesesuaian Distribusi Statistik (persamaan 3.9-3.14)

Mengukur sifat kalimat yang berhasil masuk korpus akhir dari aspek kemurnian linguistik (GlotLID) serta kesesuaian distribusi statistik berupa panjang dan keberagaman terhadap data *seed*.

### GlotLID Identification Rate & Avg Confidence (persamaan 3.9-3.10)

- **GlotLID Purity Rate**: % accepted yang detected sesuai target_lang
- **Avg GlotLID Confidence** pada accepted

Bandingkan dengan baseline NusaX train (yang sudah dihitung di proposal):

| Bahasa | Baseline NusaX | Synthetic | Gap |
|---|---|---|---|
| jav | 93.4% | ? | - |
| sun | 97.4% | ? | - |
| ace | 95.4% | ? | - |
| bjn | 95.0% | ? | - |
| mad | 96.8% | ? | - |
| min | 96.0% | ? | - |
| ban | 83.0% | ? | - |

In [5]:
# Baseline NusaX GlotLID purity (dari proposal — sudah dihitung sebelumnya)
BASELINE_PURITY = {'jav': 93.4, 'sun': 97.4, 'ace': 95.4, 'bjn': 95.0, 'mad': 96.8, 'min': 96.0, 'ban': 83.0}

rows = []
for lang in LANGS:
    if lang not in log_dfs:
        continue
    log_df = log_dfs[lang]
    accepted = log_df[log_df['outcome'] == 'accepted']
    if 'glotlid_lang' not in accepted.columns or 'glotlid_conf' not in accepted.columns:
        continue
    has_lang = accepted.dropna(subset=['glotlid_lang'])
    pure = (has_lang['glotlid_lang'] == lang).sum()
    purity = pure / len(has_lang) * 100 if len(has_lang) else 0
    avg_conf = has_lang['glotlid_conf'].mean()
    base = BASELINE_PURITY.get(lang, 0)
    rows.append({
        'lang': lang,
        'n_accepted': len(has_lang),
        'syn_purity%': round(purity, 2),
        'baseline%': base,
        'gap_pp': round(purity - base, 2),
        'avg_glotlid_conf': round(float(avg_conf), 4),
    })

display(pd.DataFrame(rows))

  lang  n_accepted  syn_purity%  baseline%  gap_pp  avg_glotlid_conf
0  ace        2268        99.16       95.4    3.76            0.9890
1  ban        2400        93.42       83.0   10.42            0.9452
2  bjn        2366        98.39       95.0    3.39            0.9809
3  jav        2430        98.40       93.4    5.00            0.9801
4  mad        2298        96.43       96.8   -0.37            0.9630
5  min        2381        98.95       96.0    2.95            0.9908
6  sun        2447        99.31       97.4    1.91            0.9898

### Self-BLEU & BLEU vs Seed (persamaan 3.11-3.12)

Dua metrik berbasis BLEU (rata-rata geometrik presisi *n-gram* termodifikasi, bobot seragam 1/N - Papineni et al., 2002; 4 orde kumulatif BLEU-2/3/4/5, BLEU-4 orde acuan):

- **Self-BLEU** (pers. 3.11; Zhu et al., 2018): keberagaman intra-label. Tiap kalimat jadi *hypothesis*, kalimat lain (label sama) jadi *references*, dirata-rata.
- **BLEU vs Seed** (pers. 3.12): kebaruan terhadap *seed*. Tiap kalimat sintetis dibandingkan ke seluruh korpus *seed* label sama.

**Best practice - kenapa |D| disetarakan ke seed.** Self-BLEU **sensitif terhadap ukuran himpunan D**: makin banyak referensi, makin tinggi nilainya. Data yang sama memberi Self-BLEU ~0,22 pada korpus penuh (~900/label) tetapi ~0,11 pada ~190/label. Karena itu nilai absolut tak bisa dibandingkan ke ambang tetap. Agar **valid**, Self-BLEU sintetis dihitung pada **|D| yang disetarakan dengan seed**, lalu dibandingkan ke **Self-BLEU seed (data manusia asli)** sebagai *baseline* keberagaman. Interpretasi: makin dekat nilai sintetis ke seed, makin setara keberagamannya dengan tulisan manusia; keduanya jauh di bawah rezim *template-repetition* (~0,5-0,9). Rumus 3.11 tidak berubah - hanya |D| yang disetarakan.

Implementasi: NLTK 3.9.4, mengikuti Texygen `SelfBleu.py` (bobot seragam + `method1`, eps=0.1). Sampel acak deterministik seed=42.

In [6]:
# B2 — Self-BLEU (pers. 3.11) & BLEU vs Seed (pers. 3.12)
# BLEU = rata-rata geometrik presisi n-gram termodifikasi, bobot seragam 1/N (Papineni et al. 2002); 4 orde kumulatif 2-5, BLEU-4 acuan.
# Implementasi ikut Texygen SelfBleu.py: bobot seragam + method1 smoothing (eps=0.1).
#
# BEST PRACTICE: Self-BLEU sensitif ukuran |D| (makin banyak referensi -> makin tinggi). Data yg sama:
#   |D|~900 -> ~0.22 ; |D|~190 -> ~0.11. Jadi Self-BLEU sintetis dihitung pada |D| DISETARAKAN ke seed,
#   lalu dibandingkan ke Self-BLEU seed (data manusia) sbg baseline. Sampel acak deterministik seed=42.
smoothie = SmoothingFunction().method1
ORDERS = (2, 3, 4, 5)
WEIGHTS = [tuple([1.0 / n] * n) for n in ORDERS]  # kumulatif orde 1..n; list-of-weights -> satu call semua orde
SAMPLE_SEED = 42


def tokenize(text):
    return text.lower().split()


def _bleu_orders(refs_tokens, hyp_tokens):
    # satu call sentence_bleu -> semua orde; BLEU-4 identik bit-per-bit dgn (0.25,)*4 tunggal
    return dict(zip(ORDERS, sentence_bleu(refs_tokens, hyp_tokens, WEIGHTS, smoothing_function=smoothie)))


def self_bleu(sentences):
    # pers. 3.11 pada himpunan D: tiap kalimat vs semua lainnya (label sama), dirata-rata
    if len(sentences) < 2:
        return {n: 0.0 for n in ORDERS}
    T = [tokenize(s) for s in sentences]
    acc = {n: [] for n in ORDERS}
    for i in range(len(T)):
        d = _bleu_orders([T[j] for j in range(len(T)) if j != i], T[i])
        for n in ORDERS:
            acc[n].append(d[n])
    return {n: float(np.mean(acc[n])) for n in ORDERS}


def bleu_vs_ref(hyps, refs):
    # pers. 3.12: tiap kalimat sintetis vs seluruh korpus seed label sama, dirata-rata
    if not hyps or not refs:
        return {n: 0.0 for n in ORDERS}
    R = [tokenize(r) for r in refs]
    acc = {n: [] for n in ORDERS}
    for h in hyps:
        d = _bleu_orders(R, tokenize(h))
        for n in ORDERS:
            acc[n].append(d[n])
    return {n: float(np.mean(acc[n])) for n in ORDERS}


def match_sample(items, n):
    # sampel acak deterministik ukuran n (menyetarakan |D| sintetis ke seed)
    if len(items) <= n:
        return list(items)
    rng = np.random.default_rng(SAMPLE_SEED)
    return [items[i] for i in rng.choice(len(items), n, replace=False)]

In [7]:
REF_ORDER = 4  # orde acuan (konfigurasi standar N=4, Papineni et al. 2002)
METRICS = [('self_syn', 'Self-BLEU sintetis'), ('self_seed', 'Self-BLEU seed'), ('bs', 'BLEU vs Seed')]

rows_head, rows_multi = [], []
for lang in LANGS:
    if lang not in syn_dfs:
        continue
    seed_df, syn_df = seed_dfs[lang], syn_dfs[lang]
    pl = {}
    for label in ['negative', 'neutral', 'positive']:
        seed_t = seed_df[seed_df['label'] == label]['text'].dropna().tolist()
        syn_all = syn_df[syn_df['label'] == label]['text'].dropna().tolist()
        if len(syn_all) < 2 or len(seed_t) < 2:
            continue
        syn_m = match_sample(syn_all, len(seed_t))       # Self-BLEU: |D| sintetis = |D| seed (adil, pers. 3.11)
        pl[label] = {
            'self_syn':  self_bleu(syn_m),               # keberagaman sintetis (matched ke seed)
            'self_seed': self_bleu(seed_t),              # keberagaman seed (baseline manusia)
            'bs':        bleu_vs_ref(syn_all, seed_t),   # BLEU-vs-Seed: SELURUH sintetis vs seed (pers. 3.12)
        }
    if not pl:
        continue
    macro = lambda k, n: float(np.mean([pl[l][k][n] for l in pl]))

    # Headline BLEU-4 (orde acuan) — ketiga metrik berdampingan
    rows_head.append({
        'lang': lang,
        'selfBLEU_syn':  round(macro('self_syn',  REF_ORDER), 4),
        'selfBLEU_seed': round(macro('self_seed', REF_ORDER), 4),
        'bleu_vs_seed':  round(macro('bs',        REF_ORDER), 4),
    })
    # Multi-orde BLEU-2/3/4/5 — ketiga metrik (selaras Zhu 2018, Tabel 2 & 3)
    for key, name in METRICS:
        rows_multi.append({'lang': lang, 'metrik': name,
                           **{f'BLEU-{n}': round(macro(key, n), 4) for n in ORDERS}})

print(f'HEADLINE BLEU-{REF_ORDER} (orde acuan) | Self-BLEU: |D| disamakan ke seed (~190/label, seed=42) | BLEU-vs-Seed: seluruh sintetis (pers. 3.12)')
display(pd.DataFrame(rows_head))
print('\nMULTI-ORDE BLEU-2/3/4/5 (selaras Zhu 2018) — orde tinggi lebih peka pengulangan struktur panjang')
display(pd.DataFrame(rows_multi))

HEADLINE BLEU-4 (orde acuan) | Self-BLEU: |D| disamakan ke seed (~190/label, seed=42) | BLEU-vs-Seed: seluruh sintetis (pers. 3.12)

  lang  selfBLEU_syn  selfBLEU_seed  bleu_vs_seed
0  ace        0.1080         0.0554        0.0871
1  ban        0.0910         0.0432        0.0701
2  bjn        0.1090         0.0545        0.0804
3  jav        0.1162         0.0502        0.0642
4  mad        0.0938         0.0606        0.0811
5  min        0.1066         0.0495        0.0770
6  sun        0.1149         0.0516        0.0688

MULTI-ORDE BLEU-2/3/4/5 (selaras Zhu 2018) — orde tinggi lebih peka pengulangan struktur panjang

   lang              metrik  BLEU-2  BLEU-3  BLEU-4  BLEU-5
0   ace  Self-BLEU sintetis  0.4205  0.2033  0.1080  0.0665
1   ace      Self-BLEU seed  0.2754  0.1070  0.0554  0.0370
2   ace        BLEU vs Seed  0.3560  0.1572  0.0871  0.0583
3   ban  Self-BLEU sintetis  0.3622  0.1643  0.0910  0.0609
4   ban      Self-BLEU seed  0.2162  0.0761  0.0432  0.0318
5   ban        BLEU vs Seed  0.2681  0.1178  0.0701  0.0491
6   bjn  Self-BLEU sintetis  0.4171  0.2039  0.1090  0.0669
7   bjn      Self-BLEU seed  0.2685  0.1075  0.0545  0.0371
8   bjn        BLEU vs Seed  0.3470  0.1543  0.0804  0.0516
9   jav  Self-BLEU sintetis  0.4078  0.2140  0.1162  0.0730
10  jav      Self-BLEU seed  0.2485  0.0937  0.0502  0.0358
11  jav        BLEU vs Seed  0.2985  0.1225  0.0642  0.0426
12  mad  Self-BLEU sintetis  0.3420  0.1614  0.0938  0.0645
13  mad      Self-BLEU seed  0.2700  0.1130  0.0606  0.0400
14  mad        BLEU vs Seed  0.2615  0.1307  0.0811  0.0587
15  min  Self-BLEU sintetis  0.4183  0.2110  0.1066  0.0634
16  min      Self-BLEU seed  0.2570  0.0952  0.0495  0.0351
17  min        BLEU vs Seed  0.3471  0.1512  0.0770  0.0496
18  sun  Self-BLEU sintetis  0.4321  0.2212  0.1149  0.0687
19  sun      Self-BLEU seed  0.2535  0.0974  0.0516  0.0357
20  sun        BLEU vs Seed  0.3034  0.1281  0.0688  0.0454

### Rasio Standar Deviasi Panjang & Selisih Rata-rata Panjang (persamaan 3.13-3.14)

Validasi apakah PSLM filter (`|gen_len − seed_len| ≤ 1.0σ` per label) bekerja konsisten lintas label. Compute dua metrik per (lang × label):

- **Rasio Standar Deviasi Panjang** ($R_\sigma$) — `std_ratio = syn_std / seed_std`
- **Selisih Rata-rata Panjang** ($\Delta\mu$) — `mean_diff = syn_mean − seed_mean`

**Tujuan**: memastikan match aggregate di B3 bukan akibat averaging antar label dengan distribusi berbeda (neutral umumnya lebih pendek, positive/negative lebih panjang & variatif).

**Verdict criteria** (internal script convention):
- `std_ratio 0.80–1.20` dan `|mean_diff| ≤ 5` → **OK** (filter constrain length drift sesuai design)
- `std_ratio < 0.70` → kalimat sintetis terlalu seragam dalam panjang (over-filtering atau LLM mode-collapse)
- `std_ratio > 1.20` → filter tidak cukup ketat (threshold 1σ terlalu longgar)
- `|mean_diff| > 5` → Generator cenderung menghasilkan kalimat lebih panjang atau lebih pendek dari seed secara konsisten

> **Catatan**: column code di tabel pakai snake_case (`std_ratio`, `mean_diff`) karena variable name di code; di proposal Bab III/IV dilaporkan sebagai *Rasio Standar Deviasi Panjang* ($R_\sigma$) dan *Selisih Rata-rata Panjang* ($\Delta\mu$).

In [8]:
rows = []
for lang in LANGS:
    if lang not in syn_dfs:
        continue
    seed_df, syn_df = seed_dfs[lang].copy(), syn_dfs[lang].copy()
    seed_df['wc'] = seed_df['text'].str.split().str.len()
    syn_df['wc']  = syn_df['text'].str.split().str.len()
    for label in ['negative', 'neutral', 'positive']:
        s_seed = seed_df[seed_df['label'] == label]['wc']
        s_syn  = syn_df[syn_df['label'] == label]['wc']
        if len(s_seed) > 1 and len(s_syn) > 1:
            ratio = round(s_syn.std() / s_seed.std(), 2)
            mean_diff = round(s_syn.mean() - s_seed.mean(), 1)
            verdict = 'OK' if 0.80 <= ratio <= 1.20 and abs(mean_diff) <= 5 else 'CHECK'
            rows.append({
                'lang': lang,
                'label': label,
                'seed_n': len(s_seed),
                'syn_n': len(s_syn),
                'seed_mean': round(s_seed.mean(), 1),
                'syn_mean': round(s_syn.mean(), 1),
                'mean_diff': mean_diff,
                'seed_std': round(s_seed.std(), 1),
                'syn_std': round(s_syn.std(), 1),
                'std_ratio': ratio,
                'verdict': verdict,
            })

display(pd.DataFrame(rows))

   lang     label  seed_n  syn_n  seed_mean  syn_mean  mean_diff  seed_std  syn_std  std_ratio verdict
0   ace  negative     192    927       22.5      23.2        0.8      15.0     11.6       0.78   CHECK
1   ace   neutral     119    452       14.5      15.4        0.9       9.6      6.2       0.65   CHECK
2   ace  positive     189    889       31.2      27.9       -3.2      15.4     12.0       0.78   CHECK
3   ban  negative     192    950       21.9      23.0        1.1      13.8     12.0       0.87      OK
4   ban   neutral     119    537       13.8      15.5        1.6       8.5      5.8       0.68   CHECK
5   ban  positive     189    913       30.8      28.4       -2.4      14.4     12.2       0.85      OK
6   bjn  negative     192    954       21.9      24.3        2.4      14.1     11.0       0.78   CHECK
7   bjn   neutral     119    482       13.5      15.6        2.1       8.3      5.5       0.66   CHECK
8   bjn  positive     189    930       30.6      29.2       -1.3      14.4     12.5       0.86      OK
9   jav  negative     192    948       21.8      24.0        2.2      14.2     11.5       0.81      OK
10  jav   neutral     119    547       13.6      15.2        1.6       8.5      6.8       0.80      OK
11  jav  positive     189    935       30.3      29.8       -0.5      14.1     12.6       0.89      OK
12  mad  negative     192    919       22.5      23.0        0.5      15.2     11.7       0.77   CHECK
13  mad   neutral     119    506       13.8      15.0        1.2       8.6      6.3       0.73   CHECK
14  mad  positive     189    873       31.2      27.4       -3.7      14.9     12.4       0.83      OK
15  min  negative     192    956       21.8      24.5        2.7      14.0     11.5       0.82      OK
16  min   neutral     119    490       13.4      15.6        2.1       8.1      6.1       0.76   CHECK
17  min  positive     189    935       30.3      29.2       -1.1      14.1     12.4       0.88      OK
18  sun  negative     192    959       21.9      24.9        3.0      14.1     11.8       0.84      OK
19  sun   neutral     119    556       13.6      15.8        2.2       8.1      5.7       0.70   CHECK
20  sun  positive     189    932       30.4      29.6       -0.8      14.4     12.7       0.88      OK

### (Pendukung) Distribusi Panjang Kalimat

Statistik deskriptif panjang kata (word count) sintetis vs data real (seed + valid + test) per bahasa. Pelengkap visual untuk R_sigma & Delta-mu (3.13-3.14).

In [9]:
def len_stats(df):
    df = df.copy()
    df['wc'] = df['text'].str.split().str.len()
    return {
        'n': len(df),
        'mean': round(df['wc'].mean(), 1),
        'std': round(df['wc'].std(), 1),
        'min': int(df['wc'].min()),
        'max': int(df['wc'].max()),
        'median': int(df['wc'].median()),
        'p95': int(df['wc'].quantile(0.95)),
    }

rows = []
for lang in LANGS:
    if lang not in syn_dfs:
        continue
    rows.append({'lang': lang, 'split': 'seed', **len_stats(seed_dfs[lang])})
    rows.append({'lang': lang, 'split': 'syn',  **len_stats(syn_dfs[lang])})
    if lang in valid_dfs:
        rows.append({'lang': lang, 'split': 'valid', **len_stats(valid_dfs[lang])})
    if lang in test_dfs:
        rows.append({'lang': lang, 'split': 'test',  **len_stats(test_dfs[lang])})

display(pd.DataFrame(rows))

   lang  split     n  mean   std  min  max  median  p95
0   ace   seed   500  23.9  15.4    4   94      20   56
1   ace    syn  2268  23.5  11.8    4   77      21   52
2   ace  valid   100  23.4  13.9    4   68      20   51
3   ace   test   400  24.1  15.2    4   75      20   57
4   ban   seed   500  23.4  14.6    3   71      19   53
5   ban    syn  2400  23.4  12.0    5   67      20   52
6   ban  valid   100  23.4  13.5    4   64      21   48
7   ban   test   400  23.5  14.5    5   68      20   57
8   bjn   seed   500  23.2  14.6    4   77      19   53
9   bjn    syn  2366  24.5  11.9    4   71      21   54
10  bjn  valid   100  22.8  13.0    4   60      20   46
11  bjn   test   400  23.2  14.5    1   69      19   54
12  jav   seed   500  23.1  14.5    4   76      19   53
13  jav    syn  2430  24.3  12.4    4   76      22   53
14  jav  valid   100  22.7  13.2    5   62      20   47
15  jav   test   400  23.1  14.4    5   70      19   55
16  mad   seed   500  23.7  15.3    4   74      19   56
17  mad    syn  2298  22.9  12.0    4   72      20   53
18  mad  valid   100  23.7  14.2    4   72      21   51
19  mad   test   400  24.0  15.2    5   78      20   57
20  min   seed   500  23.1  14.4    4   76      19   53
21  min    syn  2381  24.5  12.1    4   66      22   54
22  min  valid   100  22.7  13.3    5   61      20   47
23  min   test   400  23.3  14.4    5   71      19   56
24  sun   seed   500  23.1  14.5    1   76      19   54
25  sun    syn  2447  24.6  12.3    4   80      21   54
26  sun  valid   100  22.6  13.2    4   58      20   47
27  sun   test   400  23.2  14.3    5   70      19   53

### (Pendukung) Distribusi Label

Perbandingan distribusi label sintetis vs seed per bahasa. Konfirmasi tidak ada pergeseran class imbalance. Pelengkap kualitatif.

In [10]:
rows = []
for lang in LANGS:
    if lang not in syn_dfs:
        continue
    seed_dist = seed_dfs[lang]['label'].value_counts(normalize=True) * 100
    syn_dist = syn_dfs[lang]['label'].value_counts(normalize=True) * 100
    rows.append({
        'lang': lang,
        'seed_neg%': round(seed_dist.get('negative', 0), 1),
        'syn_neg%':  round(syn_dist.get('negative', 0), 1),
        'diff_neg':  round(syn_dist.get('negative', 0) - seed_dist.get('negative', 0), 1),
        'seed_neu%': round(seed_dist.get('neutral', 0), 1),
        'syn_neu%':  round(syn_dist.get('neutral', 0), 1),
        'diff_neu':  round(syn_dist.get('neutral', 0) - seed_dist.get('neutral', 0), 1),
        'seed_pos%': round(seed_dist.get('positive', 0), 1),
        'syn_pos%':  round(syn_dist.get('positive', 0), 1),
        'diff_pos':  round(syn_dist.get('positive', 0) - seed_dist.get('positive', 0), 1),
    })

display(pd.DataFrame(rows))

  lang  seed_neg%  syn_neg%  diff_neg  seed_neu%  syn_neu%  diff_neu  seed_pos%  syn_pos%  diff_pos
0  ace       38.4      40.9       2.5       23.8      19.9      -3.9       37.8      39.2       1.4
1  ban       38.4      39.6       1.2       23.8      22.4      -1.4       37.8      38.0       0.2
2  bjn       38.4      40.3       1.9       23.8      20.4      -3.4       37.8      39.3       1.5
3  jav       38.4      39.0       0.6       23.8      22.5      -1.3       37.8      38.5       0.7
4  mad       38.4      40.0       1.6       23.8      22.0      -1.8       37.8      38.0       0.2
5  min       38.4      40.2       1.8       23.8      20.6      -3.2       37.8      39.3       1.5
6  sun       38.4      39.2       0.8       23.8      22.7      -1.1       37.8      38.1       0.3

### (Pendukung) Volume Output & Kesesuaian Label

Volume output (yield/shortfall vs target) dan kecocokan distribusi label sintetis vs seed. Pelengkap kualitatif, bukan persamaan docx.

In [11]:
rows = []
for lang in LANGS:
    if lang not in syn_dfs:
        continue
    seed_df = seed_dfs[lang]
    syn_df = syn_dfs[lang]
    # Target ideal: SENTENCES_PER_SEED per seed
    expected = len(seed_df) * SENTENCES_PER_SEED
    actual = len(syn_df)
    seed_dist = seed_df['label'].value_counts(normalize=True)
    syn_dist = syn_df['label'].value_counts(normalize=True)
    rows.append({
        'lang': lang,
        'seed_count': len(seed_df),
        'expected': expected,
        'actual_synth': actual,
        'shortfall': expected - actual,
        'yield%': round(actual / expected * 100, 2),
        'seed_neg%': round(seed_dist.get('negative', 0) * 100, 1),
        'seed_neu%': round(seed_dist.get('neutral', 0) * 100, 1),
        'seed_pos%': round(seed_dist.get('positive', 0) * 100, 1),
        'syn_neg%':  round(syn_dist.get('negative', 0) * 100, 1),
        'syn_neu%':  round(syn_dist.get('neutral', 0) * 100, 1),
        'syn_pos%':  round(syn_dist.get('positive', 0) * 100, 1),
    })

display(pd.DataFrame(rows))

  lang  seed_count  expected  actual_synth  shortfall  yield%  seed_neg%  seed_neu%  seed_pos%  syn_neg%  syn_neu%  syn_pos%
0  ace         500      2500          2268        232   90.72       38.4       23.8       37.8      40.9      19.9      39.2
1  ban         500      2500          2400        100   96.00       38.4       23.8       37.8      39.6      22.4      38.0
2  bjn         500      2500          2366        134   94.64       38.4       23.8       37.8      40.3      20.4      39.3
3  jav         500      2500          2430         70   97.20       38.4       23.8       37.8      39.0      22.5      38.5
4  mad         500      2500          2298        202   91.92       38.4       23.8       37.8      40.0      22.0      38.0
5  min         500      2500          2381        119   95.24       38.4       23.8       37.8      40.2      20.6      39.3
6  sun         500      2500          2447         53   97.88       38.4       23.8       37.8      39.2      22.7      38.1

## 3. Konsistensi LLM terhadap Prediksi Classifier (persamaan 3.15-3.16)

Mengukur seberapa sering keputusan akhir LLM (*accepted*) bertentangan dengan prediksi *classifier* acuan. Memvalidasi bahwa validator tidak sekadar mengikuti *classifier*, melainkan menerapkan *reasoning* tersendiri. Bersifat eksploratif, tanpa target nilai absolut.

### NusaBERT-LLM Conflict Rate (persamaan 3.15)

Persentase kalimat *accepted* dengan prediksi NusaBERT berbeda dari label sentimen target. Reject-reason distribution di sel berikutnya = **(Pendukung)** kualitatif.

In [12]:
# A2. NusaBERT-LLM Conflict Rate
rows = []
for lang in LANGS:
    if lang not in log_dfs:
        continue
    log_df = log_dfs[lang]
    accepted = log_df[log_df['outcome'] == 'accepted']
    if 'nusabert_label' not in accepted.columns or 'target_label' not in accepted.columns:
        continue
    has_label = accepted.dropna(subset=['nusabert_label', 'target_label'])
    conflict = (has_label['nusabert_label'] != has_label['target_label']).sum()
    rows.append({
        'lang': lang,
        'n_accepted': len(has_label),
        'nusabert_conflict': conflict,
        'conflict_rate%': round(conflict / len(has_label) * 100, 2) if len(has_label) else 0,
    })

print('NusaBERT-LLM Conflict Rate:')
display(pd.DataFrame(rows))

NusaBERT-LLM Conflict Rate:

  lang  n_accepted  nusabert_conflict  conflict_rate%
0  ace        2268                230           10.14
1  ban        2400                209            8.71
2  bjn        2366                149            6.30
3  jav        2430                147            6.05
4  mad        2298                223            9.70
5  min        2381                295           12.39
6  sun        2447                130            5.31

In [13]:
# A2b: SV rejection reason distribution
print('SV Rejection Reasons:')
for lang in LANGS:
    if lang not in log_dfs:
        continue
    log_df = log_dfs[lang]
    sv_rejects = log_df[(log_df['outcome'].isin(['retried', 'discarded'])) & (log_df.get('sv_verdict') == 'REJECT')]
    if 'sv_feedback' not in sv_rejects.columns or len(sv_rejects) == 0:
        continue
    print(f'\n[{lang}] n={len(sv_rejects)}')
    # Truncate long reasons for display
    reasons = sv_rejects['sv_feedback'].dropna().str[:120].value_counts().head(5)
    for reason, count in reasons.items():
        print(f'  {count:>3}  {reason}')

SV Rejection Reasons:

[ace] n=555
    6  The sentence expresses a positive sentiment, not neutral.
    3  The sentence expresses dissatisfaction, which is negative sentiment.
    2  The sentence is semantically ambiguous and does not clearly or unambiguously express a negative sentiment.
    2  The sentence expresses a subjective opinion/advice rather than a neutral statement.
    2  The sentence expresses a negative opinion about the nature of the work.

[ban] n=347
    2  The sentence is promotional and persuasive, not neutral.
    2  The sentence expresses disappointment and frustration.
    1  The sentence is phrased as a question, making the negative sentiment less direct and clear.
    1  The sentence is phrased as a suggestion for improvement rather than a direct expression of negative sentiment.
    1  The sentence relies on sarcasm which can be ambiguous and does not clearly express a negative sentiment in a straightfor

[bjn] n=443
    2  The sentence expresses a positive sentiment, not neutral.
    2  The sentence expresses subjective positive sentiment ('nyaman banar').
    1  The sentence is framed as a neutral inquiry or question rather than a direct expression of negative sentiment.
    1  The sentence is an inquiry/request for advice rather than a direct expression of negative sentiment.
    1  The sentence expresses a positive sentiment regarding the taste, contradicting the negative target label.

[jav] n=335
    2  The sentence expresses a subjective opinion/preference regarding leadership qualities.
    1  The sentence is framed as a rhetorical question rather than a direct negative assertion, making the sentiment expression
    1  The sentence contains mixed sentiment by acknowledging the restaurant's value as a cheap option.
    1  The sentence is advisory and lacks a clear, strong expression of negative sentiment from the speaker.
    1  The sentence is a suggestion for a solution rather than an expression of negative sentiment.

[mad] n=411
    2  The sentence is incoherent and lacks a clear negative sentiment.
    2  The sentence expresses a positive sentiment, not neutral.
    2  The sentence is phrased as a question, which is not a neutral statement of fact.
    2  The sentence expresses a subjective preference and positive evaluation.
    2  The sentence is phrased as a question rather than a direct positive statement.

[min] n=459
    4  The sentence expresses negative sentiment regarding the restaurant experience.
    4  The sentence expresses a negative experience, not a positive one.
    2  The sentence is an inquiry/question, not a neutral statement.
    2  The sentence expresses frustration and complaint, which is not neutral.
    1  The sentence is a comparative recommendation for street food rather than a direct negative critique of the restaurant.

[sun] n=358
    3  The sentence is clearly positive, not neutral.
    2  The sentence is a speculative question rather than a neutral statement of fact.
    2  The sentence conveys a subjective opinion/preference rather than a neutral statement.
    2  Contains subjective positive sentiment ('kualitasna saé').
    2  The sentence is a suggestion for improvement, not a positive expression.

### GlotLID-LLM Conflict Rate (persamaan 3.16)

Persentase kalimat *accepted* dengan prediksi GlotLID berbeda dari bahasa target. Reject-reason distribution di sel berikutnya = **(Pendukung)** kualitatif.

In [14]:
# A3. GlotLID-LLM Conflict Rate
rows = []
for lang in LANGS:
    if lang not in log_dfs:
        continue
    log_df = log_dfs[lang]
    accepted = log_df[log_df['outcome'] == 'accepted']
    if 'glotlid_lang' not in accepted.columns or 'target_lang' not in accepted.columns:
        continue
    has_lang = accepted.dropna(subset=['glotlid_lang', 'target_lang'])
    conflict = (has_lang['glotlid_lang'] != has_lang['target_lang']).sum()
    rows.append({
        'lang': lang,
        'n_accepted': len(has_lang),
        'glotlid_conflict': conflict,
        'conflict_rate%': round(conflict / len(has_lang) * 100, 2) if len(has_lang) else 0,
    })

print('GlotLID-LLM Conflict Rate:')
display(pd.DataFrame(rows))

GlotLID-LLM Conflict Rate:

  lang  n_accepted  glotlid_conflict  conflict_rate%
0  ace        2268                19            0.84
1  ban        2400               158            6.58
2  bjn        2366                38            1.61
3  jav        2430                39            1.60
4  mad        2298                82            3.57
5  min        2381                25            1.05
6  sun        2447                17            0.69

In [15]:
# A3b: LV rejection reason
print('LV Rejection Reasons:')
for lang in LANGS:
    if lang not in log_dfs:
        continue
    log_df = log_dfs[lang]
    lv_rejects = log_df[(log_df['outcome'].isin(['retried', 'discarded'])) & (log_df.get('lv_verdict') == 'REJECT')]
    if 'lv_feedback' not in lv_rejects.columns or len(lv_rejects) == 0:
        continue
    print(f'\n[{lang}] n={len(lv_rejects)}')
    reasons = lv_rejects['lv_feedback'].dropna().str[:120].value_counts().head(5)
    for reason, count in reasons.items():
        print(f'  {count:>3}  {reason}')

LV Rejection Reasons:

[ace] n=548
   16  The sentence is written in Indonesian, not Acehnese.
    7  The phrasing is unnatural and sounds like translationese.
    7  The text is written in Indonesian, failing to meet the target language requirement.
    5  The text is in Indonesian, not Acehnese.
    5  The sentence is written in Indonesian, failing to meet the target language requirement.

[ban] n=232
   29  The sentence is written in Indonesian, not Balinese.
   10  The text is written in Indonesian, failing to meet the target language requirement.
    7  The text is written in Indonesian, not Balinese.
    5  The text is in Indonesian, not Balinese.
    4  The text is predominantly Indonesian and does not reflect Balinese linguistic structure.

[bjn] n=306
   14  The sentence is written in standard Indonesian, not Banjarese.
   12  The sentence is written in standard Indonesian, failing to use Banjarese vocabulary or grammatical structures.
   11  The sentence is entirely in Indonesian, failing to meet the target language requirement.
    8  The sentence is in Indonesian, not Banjarese.
    8  The sentence is entirely in Indonesian, not Banjarese.

[jav] n=62
    5  The text is written in Indonesian, failing the target language requirement.
    5  The text is written in Indonesian, not the target language (Javanese).
    1  Uses Indonesian 'Kenapa' instead of Javanese 'Yagene' or 'Kenangapa'.
    1  The phrasing 'operasi toko iki pancen ora profesional' sounds unnatural and like translationese.
    1  The tone shifts abruptly from a casual narrative to a formal, bureaucratic critique that sounds like a direct translatio

[mad] n=673
   18  The text is written in Indonesian, failing to meet the target language requirement.
   11  The phrasing is unnatural and sounds like translationese.
    9  The text is written in Indonesian, not the target language (Madurese).
    9  The sentence is written in Javanese, not Madurese.
    8  The text is written in Indonesian, failing to meet the target language requirement of Madurese.

[min] n=216
    2  Stilted, formal phrasing that does not reflect natural Minangkabau speech patterns.
    2  The sentence structure is too formal and follows Indonesian syntax rather than natural Minangkabau conversational style.
    2  The sentence is written in standard Indonesian, not Minangkabau.
    1  The phrasing 'barubah sadonyo' is unnatural and sounds like a literal translation of Indonesian/English, failing to conv
    1  The word 'menyiksokan' is an awkward hybrid that does not sound natural in Minangkabau.

[sun] n=65
    4  The presence of the '#' symbol makes the text unnatural and likely a formatting error.
    3  The phrasing is unnatural and sounds like translationese.
    2  Uses Indonesian loanword 'keterlibatan' instead of more natural Sundanese alternatives.
    1  Contains an Indonesian word ('mengecewakan') that disrupts the linguistic consistency of the Sundanese sentence.
    1  The word 'Rugimaneh' is not a valid Sundanese word and makes the sentence incoherent.

In [16]:
# ===== RINGKASAN AGREGAT — angka yang dilaporkan di prosa Bab IV (semua reproducible di sini) =====
# Prosa docx melaporkan RINGKASAN (rata-rata 7 bahasa / semua sel), sel-sel di atas per-bahasa/per-label.
print('=' * 66); print('AGREGAT 7 BAHASA — angka Bab IV'); print('=' * 66)

# 1. Pipeline Outcome Breakdown (pers. 3.1-3.8)
a0 = a1 = a2 = disc = dedup = 0
for lang in LANGS:
    if lang not in log_dfs: continue
    acc = log_dfs[lang][log_dfs[lang]['outcome'] == 'accepted']
    ad = acc['retry_count'].value_counts().to_dict()
    a0 += ad.get(0, 0); a1 += ad.get(1, 0); a2 += ad.get(2, 0)
    o = log_dfs[lang]['outcome'].value_counts()
    disc += o.get('discarded', 0); dedup += o.get('dedup_filtered', 0)
N = a0 + a1 + a2 + disc + dedup
print(f'\n1. Pipeline Outcome (N_terminal={N}):')
print(f'   Filter Rate={(a0+a1+a2)/N*100:.2f}%  Attempt0={a0/N*100:.2f}%  Attempt1={a1/N*100:.2f}%  '
      f'Attempt2={a2/N*100:.2f}%  Discard={disc/N*100:.2f}%  Dedup={dedup/N*100:.2f}%')

# 2. GlotLID Identification Rate & Avg Confidence (pers. 3.9-3.10)
tp = tn = cs = 0
for lang in LANGS:
    if lang not in log_dfs: continue
    acc = log_dfs[lang][log_dfs[lang]['outcome'] == 'accepted'].dropna(subset=['glotlid_lang'])
    tp += (acc['glotlid_lang'] == lang).sum(); tn += len(acc); cs += acc['glotlid_conf'].sum()
print(f'\n2. GlotLID Identification Rate={tp/tn*100:.2f}%  Avg Confidence={cs/tn:.4f}')

# 3. Self-BLEU & BLEU vs Seed (pers. 3.11-3.12) — mean 7 bahasa, BLEU-4 acuan (pakai rows_head/rows_multi)
h = pd.DataFrame(rows_head); mm = pd.DataFrame(rows_multi)
print(f'\n3. Self-BLEU sintetis={h["selfBLEU_syn"].mean():.4f}  Self-BLEU seed={h["selfBLEU_seed"].mean():.4f}  '
      f'BLEU vs Seed={h["bleu_vs_seed"].mean():.4f}')
for name in ['Self-BLEU sintetis', 'Self-BLEU seed', 'BLEU vs Seed']:
    s = mm[mm['metrik'] == name]
    vals = '  '.join('BLEU-%d=%.4f' % (n, s['BLEU-%d' % n].mean()) for n in ORDERS)
    print(f'   {name:20} {vals}')

# 4. Rasio Std Panjang (R_sigma) & Selisih Rata Panjang (Delta_mu) (pers. 3.13-3.14)
rr = []
for lang in LANGS:
    if lang not in syn_dfs: continue
    sd = seed_dfs[lang].copy(); yd = syn_dfs[lang].copy()
    sd['wc'] = sd['text'].str.split().str.len(); yd['wc'] = yd['text'].str.split().str.len()
    for lab in ['negative', 'neutral', 'positive']:
        a = sd[sd['label'] == lab]['wc']; b = yd[yd['label'] == lab]['wc']
        if len(a) > 1 and len(b) > 1:
            rr.append({'label': lab, 'R': b.std() / a.std(), 'D': b.mean() - a.mean()})
rd = pd.DataFrame(rr)
print(f'\n4. R_sigma rata-rata={rd["R"].mean():.2f}  Delta_mu rata-rata={rd["D"].mean():+.2f} kata')
for lab in ['negative', 'neutral', 'positive']:
    s = rd[rd['label'] == lab]
    print(f'   {lab:9} R_sigma={s["R"].mean():.2f}  Delta_mu={s["D"].mean():+.2f}')

# 5. Conflict Rate (pers. 3.15-3.16)
nc = nn = gcf = gn = 0
for lang in LANGS:
    if lang not in log_dfs: continue
    acc = log_dfs[lang][log_dfs[lang]['outcome'] == 'accepted']
    hn = acc.dropna(subset=['nusabert_label', 'target_label']); nc += (hn['nusabert_label'] != hn['target_label']).sum(); nn += len(hn)
    hg = acc.dropna(subset=['glotlid_lang', 'target_lang']); gcf += (hg['glotlid_lang'] != hg['target_lang']).sum(); gn += len(hg)
print(f'\n5. NusaBERT-LLM Conflict Rate={nc/nn*100:.2f}%  GlotLID-LLM Conflict Rate={gcf/gn*100:.2f}%')

# 6. Dekomposisi Pemicu Retry (pendukung) — dari df_retry TOTAL
_t = df_retry[df_retry['lang'] == 'TOTAL'].iloc[0]
print(f'\n6. Retry trigger: PSLM={_t["PSLM%"]}%  SV={_t["SV%"]}%  LV={_t["LV%"]}%  (total {_t["N_retry"]} event)')

==================================================================
AGREGAT 7 BAHASA — angka Bab IV
==================================================================

1. Pipeline Outcome (N_terminal=17500):
   Filter Rate=94.80%  Attempt0=61.59%  Attempt1=28.21%  Attempt2=5.01%  Discard=4.65%  Dedup=0.55%

2. GlotLID Identification Rate=97.72%  Avg Confidence=0.9770

3. Self-BLEU sintetis=0.1056  Self-BLEU seed=0.0521  BLEU vs Seed=0.0755
   Self-BLEU sintetis   BLEU-2=0.4000  BLEU-3=0.1970  BLEU-4=0.1056  BLEU-5=0.0663
   Self-BLEU seed       BLEU-2=0.2556  BLEU-3=0.0986  BLEU-4=0.0521  BLEU-5=0.0361
   BLEU vs Seed         BLEU-2=0.3117  BLEU-3=0.1374  BLEU-4=0.0755  BLEU-5=0.0508

4. R_sigma rata-rata=0.79  Delta_mu rata-rata=+0.53 kata
   negative  R_sigma=0.81  Delta_mu=+1.79
   neutral   R_sigma=0.71  Delta_mu=+1.68
   positive  R_sigma=0.86  Delta_mu=-1.87

5. NusaBERT-LLM Conflict Rate=8.34%  GlotLID-LLM Conflict Rate=2.28%

6. Retry trigger: PSLM=48.0%  SV=29.1%  LV=22.9%  (total 8418 event)

# Ringkasan untuk Bab IV

Tabel di atas siap di-paste ke Bab IV, mengikuti struktur prosa docx (Evaluasi Kualitas Data Sintetis):

1. **Pipeline Outcome Breakdown** (pers. 3.1-3.8) - Attempt 0/1/2, Discard, Dedup, Filter Rate.
2. **Kemurnian Linguistik & Kesesuaian Distribusi Statistik** (pers. 3.9-3.14) - GlotLID purity+conf, Self-BLEU & BLEU vs Seed (BLEU-2/3/4/5), R_sigma & Delta-mu.
3. **Konsistensi LLM terhadap Prediksi Classifier** (pers. 3.15-3.16) - NusaBERT-LLM & GlotLID-LLM Conflict Rate.

Sel **(Pendukung)/(+)** = pembahasan kualitatif (reject reasons, distribusi deskriptif), bukan persamaan docx.

**Evaluasi Performa Downstream Task** (F1-Macro & Accuracy, baseline vs augmentasi) -> `finetune_nusabert.ipynb`.